import "package:flutter/material.dart";

class MaterialTheme {
  final TextTheme textTheme;

  const MaterialTheme(this.textTheme);

  ThemeData lightScheme() {
    return ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff656015),
        surfaceTint: Color(0xff656015),
        onPrimary: Color(0xffffffff),
        primaryContainer: Color(0xffede68c),
        onPrimaryContainer: Color(0xff4d4800),
        secondary: Color(0xff006874),
        onSecondary: Color(0xffffffff),
        secondaryContainer: Color(0xff9eeffd),
        onSecondaryContainer: Color(0xff004f58),
        tertiary: Color(0xff1c6586),
        onTertiary: Color(0xffffffff),
        tertiaryContainer: Color(0xffc4e7ff),
        onTertiaryContainer: Color(0xff004c69),
        error: Color(0xffba1a1a),
        onError: Color(0xffffffff),
        errorContainer: Color(0xffffdad6),
        onErrorContainer: Color(0xff93000a),
        surface: Color(0xfff7f9ff),
        onSurface: Color(0xff181c20),
        onSurfaceVariant: Color(0xff42474e),
        outline: Color(0xff72777f),
        outlineVariant: Color(0xffc2c7cf),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xff2d3135),
        inversePrimary: Color(0xffd0c973),
        primaryFixed: Color(0xffede68c),
        onPrimaryFixed: Color(0xff1e1c00),
        primaryFixedDim: Color(0xffd0c973),
        onPrimaryFixedVariant: Color(0xff4d4800),
        secondaryFixed: Color(0xff9eeffd),
        onSecondaryFixed: Color(0xff001f24),
        secondaryFixedDim: Color(0xff82d3e0),
        onSecondaryFixedVariant: Color(0xff004f58),
        tertiaryFixed: Color(0xffc4e7ff),
        onTertiaryFixed: Color(0xff001e2c),
        tertiaryFixedDim: Color(0xff90cef3),
        onTertiaryFixedVariant: Color(0xff004c69),
        surfaceDim: Color(0xffd8dae0),
        surfaceBright: Color(0xfff7f9ff),
        surfaceContainerLowest: Color(0xffffffff),
        surfaceContainerLow: Color(0xfff1f3f9),
        surfaceContainer: Color(0xffeceef4),
        surfaceContainerHigh: Color(0xffe6e8ee),
        surfaceContainerHighest: Color(0xffe0e2e8),
      ),
      textTheme: textTheme,
    );
  }

  ThemeData darkScheme() {
    return ThemeData(
      colorScheme: ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffd0c973),
        surfaceTint: Color(0xffd0c973),
        onPrimary: Color(0xff353200),
        primaryContainer: Color(0xff4d4800),
        onPrimaryContainer: Color(0xffede68c),
        secondary: Color(0xff82d3e0),
        onSecondary: Color(0xff00363d),
        secondaryContainer: Color(0xff004f58),
        onSecondaryContainer: Color(0xff9eeffd),
        tertiary: Color(0xff90cef3),
        onTertiary: Color(0xff00344a),
        tertiaryContainer: Color(0xff004c69),
        onTertiaryContainer: Color(0xffc4e7ff),
        error: Color(0xffffb4ab),
        onError: Color(0xff690005),
        errorContainer: Color(0xff93000a),
        onErrorContainer: Color(0xffffdad6),
        surface: Color(0xff101418),
        onSurface: Color(0xffe0e2e8),
        onSurfaceVariant: Color(0xffc2c7cf),
        outline: Color(0xff8c9199),
        outlineVariant: Color(0xff42474e),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xffe0e2e8),
        inversePrimary: Color(0xff656015),
        primaryFixed: Color(0xffede68c),
        onPrimaryFixed: Color(0xff1e1c00),
        primaryFixedDim: Color(0xffd0c973),
        onPrimaryFixedVariant: Color(0xff4d4800),
        secondaryFixed: Color(0xff9eeffd),
        onSecondaryFixed: Color(0xff001f24),
        secondaryFixedDim: Color(0xff82d3e0),
        onSecondaryFixedVariant: Color(0xff004f58),
        tertiaryFixed: Color(0xffc4e7ff),
        onTertiaryFixed: Color(0xff001e2c),
        tertiaryFixedDim: Color(0xff90cef3),
        onTertiaryFixedVariant: Color(0xff004c69),
        surfaceDim: Color(0xff101418),
        surfaceBright: Color(0xff36393e),
        surfaceContainerLowest: Color(0xff0b0e12),
        surfaceContainerLow: Color(0xff181c20),
        surfaceContainer: Color(0xff1c2024),
        surfaceContainerHigh: Color(0xff272a2f),
        surfaceContainerHighest: Color(0xff323539),
      ),
      textTheme: textTheme,
    );
  }

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
    useMaterial3: true,
    brightness: colorScheme.brightness,
    colorScheme: colorScheme,
    textTheme: textTheme.apply(
      bodyColor: colorScheme.onSurface,
      displayColor: colorScheme.onSurface,
    ),
    scaffoldBackgroundColor: colorScheme.surface,
    canvasColor: colorScheme.surface,
  );
}
